version: '3.8'
services:
  resonance-redis:
    image: redis
    container_name: resonance-redis

  resonance-api:
    build:
      context: ./resonance-api
      dockerfile: Dockerfile
    container_name: resonance-api
    environment:
      - REDIS_ADDR=resonance-redis:6379

  resonance-dataserver:
    build:
      context: ./resonance-dataserver
      dockerfile: Dockerfile
    container_name: resonance-dataserver
    environment:
      - REDIS_ADDR=resonance-redis:6379
    ports:
      - "8080:8080"
