version: '3.8'
services:
  resonance-redis:
    image: redis
    container_name: resonance-redis

  resonance-microservice:
    build:
      context: ./resonance-microservice
      dockerfile: Dockerfile
    container_name: resonance-microservice
    environment:
      - REDIS_ADDR=resonance-redis:6379

  resonance-dataserver:
    build:
      context: ./resonance-dataserver
      dockerfile: Dockerfile
    container_name: resonance-dataserver
    environment:
      - REDIS_ADDR=resonance-redis:6379
    ports:
      - "8080:8080"
