version: '3.8'
services:
  resonance-redis:
    image: redis
    restart: always
    container_name: resonance-redis
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "4"

  resonance-microservice:
    depends_on:
      - resonance-redis
    build:
      context: ./resonance-microservice
      dockerfile: Dockerfile
    container_name: resonance-microservice
    restart: always
    environment:
      - REDIS_ADDR=resonance-redis:6379
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "4"

  resonance-dataserver:
    depends_on:
      - resonance-microservice
    build:
      context: ./resonance-dataserver
      dockerfile: Dockerfile
    container_name: resonance-dataserver
    restart: always
    volumes:
      - /data/resodata/server:/data
    environment:
      - REDIS_ADDR=resonance-redis:6379
    ports:
      - "18081:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "4"
