version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  resonance-api:
    build:
      context: ./resonance-api
      dockerfile: Dockerfile
    container_name: resonance-api
    environment:
      - REDIS_ADDR=redis:6379

  resonance-dataserver:
    build:
      context: ./resonance-dataserver
      dockerfile: Dockerfile
    container_name: resonance-dataserver
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "8080:8080"
